"""change avatar_url to TEXT

Revision ID: a7c0b79647b7
Revises: 269633deec9e
Create Date: 2026-06-14 01:09:18.799413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c0b79647b7'
down_revision = '269633deec9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.alter_column('avatar_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.alter_column('avatar_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
